### ISSUE TITLE
adapting node_python for other python scripts

### ISSUE THREAD

**Issue by helphelpplease** [petranb2/node_python#2]
hello, I am not technical, and trying to self-teach. Apologises if questions are daft in anyway.

Could your node_python project be easily adapted to call other simple python scripts and work with another node.js project
e.g. replace the code in script1.py with the my python script, keeping name script1.py?
e.g. add index.js to the existing project.js

Script 1: is saying hello. I could not see how to pass arguments to script 1.

Project
I want to do this locally, not in cloud.
login to web page
Execute very simple web scrape on 1 webpage (5 text elements) 
and extract result + url to a text file, all on one line.
Then repeat 20 times (repeat for next 20 records (increment url by 1) )

I have a node.js script to login, and write to a text file but it does something else. 
Plus I found another tutorial python script that extract from form 
https://www.thepythoncode.com/code/extracting-and-submitting-web-page-forms-in-python

Thankyou for your time

**Comment by petranb2** [comment]
Hi,
you can pass arguments inside the python script with : 
```js
// spawn new child process to call the python script
 const python = spawn(‘python’, [‘script2.py’,’node.js’,’python’]);
```
get the params from python script
```python
import sys
print('#Hello from python#')
print('First param:'+sys.argv[1]+'#')
print('Second param:'+sys.argv[2]+'#')
```
